zend_extension=xdebug.so

; allow xdebug connecting to the listening client (in our case, PHPStorm)
xdebug.remote_enable=1
; this special hostname means our host machine, it allows you to address the host machine from inside of the container
xdebug.client_host=host.docker.internal
; define a port for the PHPStorm to listen (see below)
xdebug.client_port=9003
; log what is happening to the file (just in case something goes wrong)
;xdebug.remote_log=/var/log/xdebug.log
; Normally you need to use a specific HTTP GET/POST variable to start remote debugging (see Remote Debugging). When this setting is set to 1, Xdebug will always attempt to start a remote debugging session and try to connect to a client, even if the GET/POST/COOKIE variable was not present.
xdebug.mode=debug
